version: "3"
services:
  app:
    image: rust-os
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - ../:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    stdin_open: true
